name: Build Bicep Templates

on:
  workflow_dispatch:
  push:
    branches:
      - day-2
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Bicep Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Bicep Files
      run: |
        az bicep build --file az-trial-infra/main.bicep