name: Deploy Bicep VM

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev)'
        required: true
        default: 'dev'

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Environment
        run: |
          az deployment sub create \
            --name "deploy-${{ github.run_id }}" \
            --location eastus \
            --template-file ./environments/${{ github.event.inputs.environment }}/main.bicep \
            --parameters @./environments/${{ github.event.inputs.environment }}/parameters.json